name: vestnett
description: A new Flutter project.
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nb_utils: ^4.5.0
  http: ^0.13.3
  fl_chart: ^0.35.0
  flutter_secure_storage: ^8.0.0
  flutter_localizations:
    sdk: flutter
  # Base
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  image_picker: ^0.8.4+3
  file_picker: ^5.0.0
  shared_preferences: ^2.0.6
  dio: ^5.0.0

 #STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  # CoinPro
  dots_indicator: ^3.0.0

  syncfusion_flutter_charts: ^23.1.38
  cached_network_image: ^3.3.0
  flutter_slidable: ^3.0.0
  url_launcher: ^6.1.14
  smooth_page_indicator: ^1.1.0
  scan: 1.6.0
  auto_size_text: ^3.0.0

dependency_overrides:
  intl: ^0.18.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - images/

